# Generated by Django 6.1 on 2026-08-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockFundFlowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=10, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=32, verbose_name='股票名称')),
                ('market', models.CharField(choices=[('SH', '上海'), ('SZ', '深圳'), ('BJ', '北京'), ('UNKNOWN', '未知')], max_length=8, verbose_name='交易所')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='快照时间(已按5分钟对齐)')),
                ('latest_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最新价')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='涨跌幅(%)')),
                ('main_net_inflow', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='主力净流入(元)')),
                ('main_net_inflow_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='主力净占比(%)')),
                ('super_large_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='超大单净流入(元)')),
                ('large_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='大单净流入(元)')),
                ('medium_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='中单净流入(元)')),
                ('small_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='小单净流入(元)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '个股资金流快照',
                'verbose_name_plural': '个股资金流快照',
                'ordering': ['snapshot_time'],
                'indexes': [models.Index(fields=['stock_code', 'trade_date'], name='fundflow_st_stock_c_058959_idx'), models.Index(fields=['trade_date', 'snapshot_time'], name='fundflow_st_trade_d_5ba238_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock_code', 'snapshot_time'), name='uniq_stock_snapshot_time')],
            },
        ),
    ]
