# Generated by Django 6.1 on 2026-08-18 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='板块代码')),
                ('name', models.CharField(max_length=64, verbose_name='板块名称')),
                ('category', models.CharField(choices=[('industry', '行业板块'), ('concept', '概念板块')], db_index=True, max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SectorConstituent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=10)),
                ('stock_name', models.CharField(blank=True, max_length=32)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituents', to='fundflow.sector')),
            ],
            options={
                'indexes': [models.Index(fields=['stock_code'], name='fundflow_se_stock_c_e2b24c_idx')],
                'constraints': [models.UniqueConstraint(fields=('sector', 'stock_code'), name='uniq_sector_stock')],
            },
        ),
    ]
