# Generated by Django 6.1 on 2026-08-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundflow', '0002_sector_sectorconstituent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name'], 'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
        migrations.RemoveField(
            model_name='sector',
            name='category',
        ),
    ]
