# Generated by Django 6.1 on 2026-08-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundflow', '0003_alter_sector_options_remove_sector_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfundflowsnapshot',
            name='snapshot_time',
            field=models.DateTimeField(db_index=True, verbose_name='快照时间(已按15分钟对齐)'),
        ),
    ]
