# Generated by Django 6.1 on 2026-08-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundflow', '0004_alter_stockfundflowsnapshot_snapshot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfundflowsnapshot',
            name='turnover_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额(元)'),
        ),
        migrations.AddField(
            model_name='stockfundflowsnapshot',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='成交量(手)'),
        ),
    ]
