# Generated by Django 6.1 on 2026-08-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundflow', '0005_add_snapshot_volume_and_turnover_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EastmoneySectorFundFlowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(db_index=True, max_length=16, verbose_name='东财板块代码')),
                ('sector_name', models.CharField(max_length=64, verbose_name='东财板块名称')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='快照时间(已按15分钟对齐)')),
                ('latest_index', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='板块指数')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='涨跌幅(%)')),
                ('main_net_inflow', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='主力净流入(元)')),
                ('main_net_inflow_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='主力净占比(%)')),
                ('super_large_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='超大单净流入(元)')),
                ('large_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='大单净流入(元)')),
                ('medium_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='中单净流入(元)')),
                ('small_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='小单净流入(元)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '东财行业资金流快照',
                'verbose_name_plural': '东财行业资金流快照',
                'ordering': ['snapshot_time', 'sector_code'],
                'indexes': [models.Index(fields=['sector_code', 'trade_date'], name='fundflow_ea_sector__fcfadf_idx'), models.Index(fields=['trade_date', 'snapshot_time'], name='fundflow_ea_trade_d_94e0a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('sector_code', 'snapshot_time'), name='uniq_eastmoney_sector_snapshot_time')],
            },
        ),
    ]
