# Generated by Django 6.1 on 2026-08-26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fundflow", "0006_add_eastmoney_sector_fund_flow_snapshot"),
    ]

    operations = [
        migrations.DeleteModel(name="SectorConstituent"),
        migrations.DeleteModel(name="Sector"),
        migrations.DeleteModel(name="StockFundFlowSnapshot"),
    ]
