# Generated by Django 6.1 on 2026-08-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundflow', '0007_remove_legacy_stock_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EastmoneySectorFundFlowSnapshotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日')),
                ('snapshot_time', models.DateTimeField(db_index=True, unique=True, verbose_name='快照时间')),
                ('inflow_succeeded', models.BooleanField(verbose_name='流入榜请求成功')),
                ('outflow_succeeded', models.BooleanField(verbose_name='流出榜请求成功')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '东财行业资金流快照状态',
                'verbose_name_plural': '东财行业资金流快照状态',
                'ordering': ['snapshot_time'],
            },
        ),
    ]
