# Generated by Django 6.1 on 2026-09-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundflow', '0008_eastmoneysectorfundflowsnapshotstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eastmoneysectorfundflowsnapshotstatus',
            options={'ordering': ['snapshot_time', 'industry_level'], 'verbose_name': '东财行业资金流快照状态', 'verbose_name_plural': '东财行业资金流快照状态'},
        ),
        migrations.RemoveConstraint(
            model_name='eastmoneysectorfundflowsnapshot',
            name='uniq_eastmoney_sector_snapshot_time',
        ),
        migrations.AddField(
            model_name='eastmoneysectorfundflowsnapshot',
            name='industry_level',
            field=models.PositiveSmallIntegerField(choices=[(2, '东财二级行业'), (3, '东财三级行业')], db_index=True, default=2, verbose_name='东财行业层级'),
        ),
        migrations.AddField(
            model_name='eastmoneysectorfundflowsnapshotstatus',
            name='industry_level',
            field=models.PositiveSmallIntegerField(choices=[(2, '东财二级行业'), (3, '东财三级行业')], db_index=True, default=2, verbose_name='东财行业层级'),
        ),
        migrations.AlterField(
            model_name='eastmoneysectorfundflowsnapshotstatus',
            name='snapshot_time',
            field=models.DateTimeField(db_index=True, verbose_name='快照时间'),
        ),
        migrations.AddIndex(
            model_name='eastmoneysectorfundflowsnapshot',
            index=models.Index(fields=['industry_level', 'sector_code', 'trade_date'], name='sector_level_code_date_idx'),
        ),
        migrations.AddIndex(
            model_name='eastmoneysectorfundflowsnapshot',
            index=models.Index(fields=['industry_level', 'trade_date', 'snapshot_time'], name='sector_level_date_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='eastmoneysectorfundflowsnapshot',
            constraint=models.UniqueConstraint(fields=('industry_level', 'sector_code', 'snapshot_time'), name='uniq_eastmoney_sector_level_snapshot_time'),
        ),
        migrations.AddConstraint(
            model_name='eastmoneysectorfundflowsnapshotstatus',
            constraint=models.UniqueConstraint(fields=('industry_level', 'snapshot_time'), name='uniq_eastmoney_sector_level_status_time'),
        ),
    ]
