# Generated by Django 6.1 on 2026-09-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KaipanlaSectorFundFlowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(db_index=True, max_length=16, verbose_name='开盘啦板块代码')),
                ('sector_name', models.CharField(max_length=64, verbose_name='开盘啦板块名称')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='快照时间(已按15分钟对齐)')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='涨跌幅(%)')),
                ('main_net_inflow', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='主力净流入(元)')),
                ('main_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='主力买(元)')),
                ('main_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='主力卖(元)')),
                ('large_order_net_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='300万以上大单净额(元)')),
                ('volume_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='量比')),
                ('turnover_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='成交额(元)')),
                ('float_market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='流通市值(元)')),
                ('total_market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='总市值(元)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '开盘啦板块资金流快照',
                'verbose_name_plural': '开盘啦板块资金流快照',
                'ordering': ['snapshot_time', 'sector_code'],
                'indexes': [models.Index(fields=['sector_code', 'trade_date'], name='kaipanla_ka_sector__f356f2_idx'), models.Index(fields=['trade_date', 'snapshot_time'], name='kaipanla_ka_trade_d_e64706_idx')],
                'constraints': [models.UniqueConstraint(fields=('sector_code', 'snapshot_time'), name='uniq_kaipanla_sector_snapshot_time')],
            },
        ),
        migrations.CreateModel(
            name='KaipanlaSectorFundFlowSnapshotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='快照时间')),
                ('fetch_succeeded', models.BooleanField(verbose_name='抓取成功')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '开盘啦板块资金流快照状态',
                'verbose_name_plural': '开盘啦板块资金流快照状态',
                'ordering': ['snapshot_time'],
                'constraints': [models.UniqueConstraint(fields=('snapshot_time',), name='uniq_kaipanla_sector_status_time')],
            },
        ),
    ]
