# Generated by Django 6.1 on 2026-09-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaipanla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaipanlasectorfundflowsnapshot',
            name='snapshot_time',
            field=models.DateTimeField(db_index=True, verbose_name='快照时间(已按5分钟对齐)'),
        ),
    ]
